### PR TITLE
Fix bugs / tests with empty string default for missing assets

### PR DESCRIPTION
**Pull request by dgirardi**
- Fix a bug with _all_ possible template placeholders being incorrectly detected in some situations
- Fix some bugs introduced by https://github.com/prebid/prebid-universal-creative/pull/171 (that were caught by tests, but tests did not run on that PR)
- Enable circle tests on PRs
- Updated browser list for circleCI (using the same list used in [prebid.js](https://github.com/prebid/Prebid.js/blob/master/browsers.json))

### CODE REVIEW

**Comment by patmmccann** [comment]
@muuki88 could anyone from highfivve take a look?

**Comment by muuki88** [comment]
@anitaschiller can take at look on Tuesday. She's out of office tomorrow and Monday.

Maybe I have some time tomorrow ☺️

**Comment by muuki88** [comment]
@anitaschiller can take at look on Tuesday. She's out of office tomorrow and Monday.

Maybe I have some time tomorrow ☺️

@dgirardi can you elaborate on this statement?

> Fix a bug with all possible template placeholders being incorrectly detected in some situations

**Comment by dgirardi** [comment]
@muuki88, can you spot it? :)

```
const placeholderIndex = (~doc.body.innerHTML.indexOf(placeholder)) ? doc.body.innerHTML.indexOf(placeholder) : (doc.head.innerHTML && doc.head.innerHTML.indexOf(placeholder));
if (~placeholderIndex) {
    placeholders.push(placeholderKey);
}
```

(a refresher, `~(-1) === 0`). If the placeholder is not in `body.innerHTML` and `head.innerHTML` is falsy, the placeholder was not found but is still added to the list of found placeholders.

**Review by musikele — APPROVED** [review]
LGTM - at this point I am afraid of ask, but where is discussed/defined the syntax of using hb_native_linkurl:${AD_ID} ? There's no place in documentation for this... Or I'm unable to find...

**Review by patmmccann — APPROVED** [review]

**Pull request merged**
