### PR TITLE
updates to support renaming pbjs in universal creative

### PR DESCRIPTION
**Pull request by GLStephen**
This PR resolves the following:

https://github.com/prebid/Prebid.js/issues/3502 and https://github.com/prebid/prebid-universal-creative/issues/51

@bretg @idettman There is one remaining issue to be evaluated by Prebid maintainers and I can update the PR. That issue is that the dist folder is not in the .gitignore. It is intended to be the built version. However, that version can now diverge from the common version due to customization. I'm not sure of the best approach, but will make whatever edit is needed.

### CODE REVIEW

**Comment by jaiminpanchal27** [comment]
LGTM
@GLStephen Thanks for fixing this. Can you resolve the conflict.

**Comment by GLStephen** [comment]
@jaiminpanchal27 the conflicts may be due to "string-replace-webpack-plugin": "^0.1.3" which may make some or all of them unavoidable.

**Comment by jaiminpanchal27** [comment]
@GLStephen you remove package-lock from your PR. I will re-add after merging your PR.

**Comment by GLStephen** [comment]
@jaiminpanchal27 synced to master. Enjoy!

**Pull request merged**
