### PR TITLE
+ catching errors from postscribe library

### PR DESCRIPTION
**Pull request by ibb-jile**

### CODE REVIEW

**Comment by ibb-jile** [comment]
it's fix for this issue https://github.com/prebid/prebid-universal-creative/issues/128

**Review by jsnellbaker — APPROVED** [review]

**Comment by ibb-jile** [comment]
Hello @robertrmartinez , please, will you have some time to check this PR? it is really small bugfix. But this bug, can make a lot of troubles with creatives.

**Comment by ibb-jile** [comment]
Hello @jsnellbaker  , is possible ask more people for second review?

**Comment by NadeemQu** [comment]
Hi @robertrmartinez, could you please help us by reviewing the PR? Many thanks in advance.

**Review by jaiminpanchal27 — APPROVED** [review]

**Pull request merged**
