### PR TITLE
add appnexus and extra param support to endpoint config

### PR DESCRIPTION
**Pull request by idettman**
Added endpoint configuration for `appnexus`. 

Also, we need to pass the Rubicon account ID to satisfy our GDPR rules. This is added as part of the POST body. 

`load-cookie.html?endpoint=rubicon&args=account:1001,other:value`

### CODE REVIEW

**Comment by bretg** [comment]
Tested this and found that the limit value was a large number by default. Big enough that it caused Prebid Server to choke.

Isaac and I figured out that specifying max_sync_count was a workaround, but that value needs a default.

**Comment by bretg** [comment]
We also tried different combinations of parameters and found that it automatically adds quotes around both the attribute and the value.

I've taken a cut at updating the prebid.org docs -- https://github.com/prebid/prebid.github.io/pull/1312

**Comment by bretg** [comment]
Much better - thanks Isaac. @mkendall07 - over to you.

**Comment by bretg** [comment]
Docs PR https://github.com/prebid/prebid.github.io/pull/1312

**Comment by mkendall07** [comment]
looks ok to me but should we have a larger default value than 5? seems a bit small to me.

**Comment by bretg** [comment]
Great - how is the universal creative deployed to jsdelivr?

**Comment by mkendall07** [comment]
to deploy we use NPM. https://github.com/prebid/prebid-universal-creative#build-for-production

You'll need create an NPM user and then I can grant you access to the prebid repos.

**Pull request merged**
